name: Trading Bot

on:
  push:   # This job will run every time a push is made to the repository
  schedule:
    # This cron job runs every hour, you can modify it as needed
    - cron: '0 * * * *'

jobs:
  execute-trading-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # Correct version of checkout

    - name: Set up Python environment
      uses: actions/setup-python@v3  # Correct version of Python setup
      with:
        python-version: '3.10'  # Python version 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run trading script
      run: python 'python app.py'  # Run your Python script (change to your file name)
      env:
        APCA_API_BASE_URL: ${{ secrets.APCA_API_BASE_URL }}
        APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
        APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
