name: Trading Bot

on:
  push:   # This job will run every time a push is made to the repository
  schedule:
    # This cron job runs every hour, you can modify it as needed
          - cron: '0 * * * *'

jobs:
  execute-trading-script:
    # The job will run on the latest Ubuntu virtual environment
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      # This step checks out the repository where the code is located
      uses: actions/checkout@v3

    - name: Set up Python environment
      # Set up the correct Python version for your script
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      # Install Python packages needed for your trading bot and other APIs
      run: |
        python -m pip install --upgrade pip
        pip install alpaca-trade-api spotipy python-dotenv  # Install dependencies

    - name: Run trading script
      # Run the trading script that contains your trading logic
      run: python python app.py
      env:
        APCA_API_BASE_URL: ${{ secrets.APCA_API_BASE_URL }}
        APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
        APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
